### ISSUE TITLE
SP wrong after ROM boot

### ISSUE THREAD

**Issue by 42Bastian** [laoo/Felix#107]
SP should be 3 is 0.

**Comment by laoo** [comment]
@42Bastian What does SP mean?

**Comment by 42Bastian** [comment]
Stackpointer or S register. In the current version, it seems the ROM code is not really executed.

**Comment by laoo** [comment]
I've verified that initial value of SP in Mikey at startup is $100 (not $1ff) and the value that is at the beginning of user code at $200 is $101.

**Comment by laoo** [comment]
Initial SP value at startup is now random.
