### ISSUE TITLE
SPRSYS initial values

### ISSUE THREAD

**Issue by 42Bastian** [laoo/Felix#108]
LEFTHAND seems to be 1 after reset.

**Comment by laoo** [comment]
@42Bastian In the code everything looks fine. Do you have any code that runs differently on hardware (handy?) and on Felix, that I could verify it?

**Comment by 42Bastian** [comment]
I have an example, but need to send via PM. (nanogame for LoveByte).

**Comment by 42Bastian** [comment]
The problem is the reset value of the bit. It is different in Felix compared to a real Lynx.

**Comment by laoo** [comment]
I've done some testing. Please look at discord.

**Comment by laoo** [comment]
It turns out that it doesn't any swapping. I misundersood my code :) It returns the same values as original Lynx. Remaping is done only with screen rotation (a flag in cartridge header).
