### ISSUE TITLE
EEProm support : writing 0 value hangs the emulator

### ISSUE THREAD

**Issue by fdescharmes** [laoo/Felix#11]
EEprom is working now, but if I try to write 0 value, the EE_write BLL function seems to hang.

See this example:
[EEPROM2.zip](https://github.com/laoo/Felix/files/7482112/EEPROM2.zip)

The program is very easy:
- draw black screen
- write 1 at position 0 and draw a green rectangle
- write 0 at position 0 and draw a light green rectangle

Note:
- the .o and .lnx files work with Handy with no EEprom support
- the .o file does not works with Handy with EEPROM support (will check with LordKraken)
- the .lnx file works with Handy with EEPROM support
- the .o file does not work with Felyx
- the .lnx file does not work with Felyx

Not tested this specific program on real Lynx, but this is part of the launch game procedure in Ynxa, and it is not working on Felyx, but working on real Lynx, and Handy EEprom

**Comment by 42Bastian** [comment]
In handy the EEPROM support is by default off unless enabled in the LNX header (which an .o file does not have).

**Comment by fdescharmes** [comment]
Oh yes, forgot about this, so I won't mind about .o with Handy EEprom

**Comment by laoo** [comment]
I've added new issue #14 to set the EEPROM settings to .o files. Now it's disabled

**Comment by fdescharmes** [comment]
It works with the Ynxa ROM.
Thanks

**Comment by laoo** [comment]
@fdescharmes btw I'checked the sample on GameDrive and it behaves correctly (with two stripes)
