### ISSUE TITLE
Flip and Tate mode

### ISSUE THREAD

**Issue by fdescharmes** [laoo/Felix#114]
Tate mode is working
Flip is working in horizontal mode,

But when I use Flip in tate mode, either I get garbage, either I get screen with a small decalage (like if voff is set)
![image](https://user-images.githubusercontent.com/67586767/171374473-ddb5a8b7-dbc3-4349-a14d-72497fafdec1.png)
![image](https://user-images.githubusercontent.com/67586767/171374580-85c948ba-804b-4471-8f16-8dc8b3ddad61.png)

In fact, it depends on which buffer screen is displayed. On if full of garbage, other one scrolled a bit

**Comment by fdescharmes** [comment]
In fact, flip is not working yet (it's on the roadmap), so this is a duplicate for https://github.com/laoo/Felix/issues/6

Closed

**Comment by 42Bastian** [comment]
Looks like the start address is not correctly used. Maybe Felix adds screen size to the start of the screen. But in fact, the SW has to do it.
