### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by soundsnow** [laoo/Felix#116]
There's no a good Lynx emulator for Android
Ten years ago
aLynx Handy Android port Google Play
but now it's not the best choice
it's made for Android 2.3, for my modern Android 13, 14 phones its virtual button is hard to touch and edit
as far as i know, Felix is the only one active Atari Lynx emulator
I requested BigPEmu (closed source Jaguar emulator)'s developer for Android version, but he didn't reply to me
People are welcome to play Handheld console games with more popular handheld platforms (systems)

**Comment by laoo** [comment]
Now Felix is not mature enough, but potentially in the near future it's core could be used to drive some emulator on Android. I'm just not an Android programmer, but everyone is welcome to participate in the project.

**Comment by laoo** [comment]
Making Android version isn't in scope of this project. But i'll try to make Felix portable enough to be possible in the future.
