### ISSUE TITLE
Sprites issue

### ISSUE THREAD

**Issue by Atari260STE** [laoo/Felix#123]
![20230808_173426](https://github.com/laoo/Felix/assets/16839389/a7e9ed2e-60f8-4e27-9bee-1710d4290bf7)
[sprite_mini_20230808.zip](https://github.com/laoo/Felix/files/12303307/sprite_mini_20230808.zip)

Attached you can see that one sprite is cut under Felix 0.50.0 (167-e86868b)

**Comment by 42Bastian** [comment]
Ok, strangly, in Felix memory from $4b1 is zeroed. And thus killing the "bra"

**Comment by 42Bastian** [comment]
Fixed with latest version.

**Comment by laoo** [comment]
I assume it must have been something with collision buffer.
It indeed works now.
