### ISSUE TITLE
Glitch in "A Bug's Lynx"

### ISSUE THREAD

**Issue by laoo** [laoo/Felix#18]
![obraz](https://user-images.githubusercontent.com/6305226/140622643-cb7de352-0a32-4189-bbe3-4e4c57f39194.png)

**Comment by fdescharmes** [comment]
Tested the ROM with the 0.5.0 version and it seems the glitch is no more here
![image](https://user-images.githubusercontent.com/67586767/150776549-da1df388-e4fa-4760-8ce5-2f6b2d0edfa9.png)

**Comment by laoo** [comment]
great. So closing, as it was only this visual issue here.
