### ISSUE TITLE
APFEL_2A.O using XOR sprites does not work

### ISSUE THREAD

**Issue by laoo** [laoo/Felix#2]
XOR sprites are buggy

![obraz](https://user-images.githubusercontent.com/6305226/138689714-d72eeb55-4a95-4aec-a7cc-6b5fa72c1418.png)

**Comment by laoo** [comment]
It wasn't xor bug. It was bug in the maths. Writing to M register just cleared the overflow bug but actual write went to void.

**Comment by 42Bastian** [comment]
Please reopen. See attached boing.o: Left ball is correct when collided, right one is wrong. Seems to be a mask problem
[boinx_xor.zip](https://github.com/laoo/Felix/files/7531587/boinx_xor.zip)
.
