### ISSUE TITLE
Immediate death in Berzerkoids

### ISSUE THREAD

**Issue by laoo** [laoo/Felix#20]

**Comment by laoo** [comment]
Fixed in 0.4.6

**Comment by mikerro** [comment]
Immediate death bug seems to be fixed now. Instead of this scrren seems badly refreshed, and game locks after leaving 2 or 3 rooms.

**Comment by laoo** [comment]
@mikerro I've checked it on Lynx and the problem with screen refresh is there also, so it's a bug in the game. I haven't go past first level. Have you tried it on handy of Lynx?

**Comment by mikerro** [comment]
Tried it on Handy and reached shhoting (red) enemies. Played 2 or 3 times longer and there wasn't any lockup.

**Comment by laoo** [comment]
Reopen then

**Comment by mikerro** [comment]
No death now but I will open new issue...
