### ISSUE TITLE
Crash after title in Gauntlet

### ISSUE THREAD

**Issue by mikerro** [laoo/Felix#46]

**Comment by 42Bastian** [comment]
Actually no crash, it seems to be stuck in the checksum routine $37b-§3d8.

**Comment by 42Bastian** [comment]
Gauntlet (and maybe others) call the ROM for selecting a block ($fe00), so if boot rom does not exist, it will crash.

**Comment by laoo** [comment]
Emulated ROM has escapes for $ff80 (reset), $fe4a (cartridge decryption), $fe19 (clear RAM and initialize display) and $fe00 (shift block number). The same as in Handy. So basic functionality should work

**Comment by 42Bastian** [comment]
The handling of the B bit in the P register is the problem. I need to check the actual behavior on the real HW. But faking it to be always 0 lets Gauntlet start and run.

**Comment by laoo** [comment]
You've found a bug in CPU emulation. If 4th bit was set in a byte that was pulled from the stack to P register it wasn't discarded.

**Comment by laoo** [comment]
Fixed in 0.4.7
