### ISSUE TITLE
Rotation flag

### ISSUE THREAD

**Issue by fdescharmes** [laoo/Felix#5]
This is not a bug, but a request for enhancement.

If a ROM has rotation flag set, the game is still emulated in horizontal mode.
Is it possible to display in vertical mode (and map direction control in consequence) based on header flag ?
Or maybe there is an option to lauch the game in vertical mode va command line (for .o files) ?

Example of a ROM in vertical mode
[attack.zip](https://github.com/laoo/Felix/files/7415738/attack.zip)

**Comment by laoo** [comment]
@fdescharmes Added support for rotation flag in version 0.4.4
