### ISSUE TITLE
Garbled screen after a few seconds (no textures) in Dirty Larry (unplayable)

### ISSUE THREAD

**Issue by mikerro** [laoo/Felix#53]

**Comment by mikerro** [comment]
0.4.6 game starts and plays normally. Glitches and lockup after player's death. 
![image](https://user-images.githubusercontent.com/24191730/141556088-e537ebf1-75d3-495f-b622-3f259370eb4f.png)

**Comment by laoo** [comment]
Working in 0.5.0 (186-6fc2373) [6fc2373]
