### ISSUE TITLE
Raiden - glitches then game crash.

### ISSUE THREAD

**Issue by mikerro** [laoo/Felix#59]

**Comment by mikerro** [comment]
Now (0.5.0) game starts and plays a while then some graphics glitches appear and finally crashes. 
![image](https://user-images.githubusercontent.com/24191730/146066645-44df9e43-d708-46c2-896e-62429f916275.png)

**Comment by mikerro** [comment]
The above doesn't happen always. Must check more thoroughly.

**Comment by laoo** [comment]
Played a while and haven't found any glitches in 0.6.0
