### ISSUE TITLE
Problem with collisions in Fighter Demo (similar as in Sprdemo05)

### ISSUE THREAD

**Issue by mikerro** [laoo/Felix#64]
![image](https://user-images.githubusercontent.com/24191730/140638018-9bf9bc9a-4c08-4a04-b73c-9cba4ebbccc2.png)

**Comment by laoo** [comment]
I did not intend to close it. Good to know that github is parsing commit messages :)

**Comment by laoo** [comment]
Actually something is broken here

**Comment by laoo** [comment]
Fixed in 0.4.6
