### ISSUE TITLE
Quadrant drawing with wrong offset.

### ISSUE THREAD

**Issue by 42Bastian** [laoo/Felix#70]
The attached example draws the sprite left first. The bullet is drawn in the middle by writing directly into video mem.
But the sprite appears one pixel left.
<img width="213" alt="dl" src="https://user-images.githubusercontent.com/20296416/141610760-88fabd45-2d28-437f-89dc-eca06b0705cd.png">

[draw_left.zip](https://github.com/laoo/Felix/files/7531604/draw_left.zip)

**Comment by 42Bastian** [comment]
```
173:  int sprhpos = (int16_t)( scb.hposstrt - scb.hoff );
174:             // if ( ( (uint8_t)quadCycle[quadrant] & Suzy::SPRCTL1::DRAW_LEFT ) != ( (uint8_t)quadCycle[(size_t)suzy.mStartingQuadrant] & Suzy::SPRCTL1::DRAW_LEFT ) )
175:             //   sprhpos += dx;
```
Commenting this code fixes it, at least for the example. Need to find other examples.

**Comment by laoo** [comment]
This logic wah taken from Handy. I need to compare how the code behaves in both emulators.

And thanks for very specific test case, such cases are extremally useful

**Comment by laoo** [comment]
I've read Handy and Felix routine side by side and found a difference. If we believe Handy code, the offset should been added according to the comment:
> Take the sign of the first quad (0) as the basic sign, all other quads drawing in the other direction get offset by 1 pixel in the other direction, this fixes the squashed look on the multi-quad sprites. 

There was trivial bug that I wasn't comparing the sign to first quad, but I was offsetting starting quad twice.
