### ISSUE TITLE
Introducing GUI

### ISSUE THREAD

**Issue by laoo** [laoo/Felix#81]
Using Dear ImGui

**Comment by 42Bastian** [comment]
Something got broken. Some of the new_bll/demo files startup with wrong colors. Dropping the same file on the running instance makes them run correct.
Prominent example demo000.o:  HBL colors greenish instead of red and parts of Phoby-sprite are transparent.

**Comment by laoo** [comment]
@42Bastian Default pixel format for DX9 is reversed in comparison with DX11. It's a matter of RGBA vs BGRA. I might have mishandled it. I'll take a look into it, but newest version works OK for me.

**Comment by 42Bastian** [comment]
Pulled the latest sources, still colors are wrong.
See attached demo (besides the xor-sprite error). After dropping raw.o again colors are correct
[raw.zip](https://github.com/laoo/Felix/files/7555338/raw.zip)
.

**Comment by laoo** [comment]
I see now. It happens to me too. I haven't check release build recently. I'll search for the bug.

**Comment by laoo** [comment]
@42Bastian The problem still remains, but only for DX9 renderer. Currently I have no clue. I'll create a new issue for it.

**Comment by laoo** [comment]
Regarding topic of the issue: There is now simple File->Open dialog

**Comment by laoo** [comment]
@42Bastian I was trying to debug the xor-sprite error in the above example but I can't find any bug.
Are you able to replicate the problem in simplest possible scenario? Maybe one xor sprite drawn in the same place or something.

**Comment by laoo** [comment]
We can assume that "introduction phase" is already behind us :)
