### ISSUE TITLE
XOR-sprites are drawn  wrong

### ISSUE THREAD

**Issue by laoo** [laoo/Felix#83]

**Comment by 42Bastian** [comment]
Attached a simple example. Depending on x (odd or even) the right side of the pixel is not correct. The lower sprite is the xor one and can be moved, the upper is a normal one and does not move.
[xor_sprite.zip](https://github.com/laoo/Felix/files/7567955/xor_sprite.zip)

**Comment by laoo** [comment]
Thanks. I've found that if last pixel was left nibble it wasn't flushed properly.
