### ISSUE TITLE
Loading/executing of original ROM broken

### ISSUE THREAD

**Issue by 42Bastian** [laoo/Felix#86]
Checked, and non of my bootsector demos work anymore.

**Comment by laoo** [comment]
I don't know how to contact you effectively, as I would have told you that I've changed the ROM setting. Now only one parameter is accepted and ROM has to be set in configuration using UI
![image](https://user-images.githubusercontent.com/6305226/143772948-7a974be6-82e6-4d04-a6b9-073f941499ea.png)

**Comment by laoo** [comment]
@42Bastian Please try this and let mi know if there are some issues with this option.

**Comment by 42Bastian** [comment]
> I don't know how to contact you effectively, 

Easiest would be on discord. 

Kernel: Ah, I did not understand what you mean with "kernel". Maybe call it "boot rom"?

**Comment by 42Bastian** [comment]
Ok, choosing the right ROM works, only the settings aren't saved.

**Comment by laoo** [comment]
You have to exit the emulator cleanly. It should be saved then.

**Comment by 42Bastian** [comment]
Tried, but no. Where should it go? Ok, I can search ;-)

**Comment by laoo** [comment]
Configuration files are in c:/[user]/AppData/Local/Felix

**Comment by laoo** [comment]
I'm away from PC now. I'll recheck it later whether it still works or there is some regression.

**Comment by laoo** [comment]
@42Bastian I've checked and works on my machines.  I've got a file `c:\Users\dorot\AppData\Local\Felix\SysConfig.lua` that looks like:
```lua
singleInstance = false;
kernel = {
	useExternal = true;
	path = "C:\\Users\\dorot\\Documents\\lynxboot.img";
};
keyMapping = {
	pause   = 50;
	down    = 40;
	up      = 38;
	right   = 39;
	left    = 37;
	option1 = 49;
	option2 = 51;
	inner   = 90;
	outer   = 88;
};
```

And when I change any option and close the emulator window the content of that file changes accordingly.

**Comment by laoo** [comment]
I did some renaming and in example above there is no `kernel` but `bootROM`
![image](https://user-images.githubusercontent.com/6305226/143783608-10cd8386-00dc-4bdc-b29c-10f43af8e354.png)

**Comment by 42Bastian** [comment]
It is only saved if closed with the "x", not if closed via File->Exit

**Comment by laoo** [comment]
Thanks. Fixed.
