### ISSUE TITLE
Possible bug:  cross-page access does not work correctly

### ISSUE THREAD

**Issue by 42Bastian** [laoo/Felix#87]
The credit animation of SIMIS fails. The animation sequence contains `lda nn,x` acessess. If `nn` is close to a page boundary (xxFE), then the animation fails.
But it does not crash, pressing A|B lets the animation stop and the menu appears.
[anim.zip](https://github.com/laoo/Felix/files/7658230/anim.zip)

**Comment by 42Bastian** [comment]
Correction: It seems to be `dec nn,x`, replacing it by 
```
sec
lda nn,x
sbc #1
sta nn,x
```

works.

**Comment by 42Bastian** [comment]
Ok, found it:
```
   case Opcode::MAX_DEC:
      ++state.pc;
      state.eah = co_await fetchOperand( state.pc++ );
      state.fa = state.t = state.ea;
      state.eal += state.x;  <<<<< must be state.ea
      state.t += state.x;
      co_await read( state.ea );
      state.m1 = co_await read( state.t );
      state.m2 = dec( state.m1 );
      co_await write( state.ea, state.m2 );
      break;
```
Fixing this (and all other WAX, WAY) fixes also Dracula

**Comment by 42Bastian** [comment]
This code is also suspicious:
```
  case Opcode::RAX_CMP:
      ++state.pc;
      state.eah = co_await fetchOperand( state.pc++ );
      state.fa = state.t = state.ea;
      state.t += state.x;
      if ( state.th != state.eah )
      {
        state.eal += state.x;
        co_await read( state.ea );
      }
      state.m1 = co_await read( state.t );
      cmp( state.m1 );
      break;
```
I guess here you simulate page-crossing, but then `state.eal` should also be `state.ea`.

**Comment by laoo** [comment]
state.ea points to location before high address byte correction (the calculation is 8-bit and takes two cycles to update both address bytes if page is crossed). state.t points to correct address.
I'll debug it.

**Comment by laoo** [comment]
Yes, I see the bug now: the read is through ea but write through t. I'll correct it and refactor slightly to be more concise.

**Comment by laoo** [comment]
Fixed
