### ISSUE TITLE
Collision detection does not work.

### ISSUE THREAD

**Issue by 42Bastian** [laoo/Felix#88]
Checked with Toki. No collision detection.

**Comment by 42Bastian** [comment]
Demo from new_bll.
[boing.zip](https://github.com/laoo/Felix/files/7659905/boing.zip)

**Comment by mikerro** [comment]
No collisions in Centipede (only mushrooms) and Berzerkoids (not at all).

**Comment by laoo** [comment]
That was hard to find, but fixed. Should go to 0.5.1

**Comment by 42Bastian** [comment]
Ok, what does 'auto' in this context?

**Comment by laoo** [comment]
@42Bastian It was silly. It created a new variable `fred` with `auto`matic type deduction that hid `fred` variable from outer scope.

**Comment by laoo** [comment]
@42Bastian I changed it to make it a cleaner fix. I creat a new variable and update outer scope `fred` if this `newFred` is not empty.

**Comment by 42Bastian** [comment]
I see. Really hard to find. Maybe check if warnings can be activated which warn. At least some compiler tell if a new variable hides outer scope variables.
