### ISSUE TITLE
Only one instance can run

### ISSUE THREAD

**Issue by 42Bastian** [laoo/Felix#9]
As the title says: Only a single instance can run. Starting a second freezes the first.

**Comment by laoo** [comment]
@42Bastian Actually It's not a bug. It's a feature. It is usefull if you are launching emulator from some IDE that does building and running. It was tedious to exit emulator each time. One thing that should be done is to make it optional.
Felix is writing it's configuration to AppData folder and I'll add it such option there. Only thing we need is some GUI to configure it in civilized way.

**Comment by 42Bastian** [comment]
Ok, the idea is neat, but does not work. The original instance stops. Seems like some initialization fails.

**Comment by laoo** [comment]
@42Bastian For now I've added a possibility to disable this feature.
Go to `c:\Users\[user-name]\AppData\Local\Felix\WinConfig.lua` and edit `singleInstance`. Now by default it will be false, so there can be run multiple instances of emulator.

**Comment by laoo** [comment]
@42Bastian Can you point me to the ROM that hangs? I can't reproduce it.

**Comment by 42Bastian** [comment]
I just dropped twice APB.lnx. But any other shows the same effect.

**Comment by laoo** [comment]
@42Bastian Problem still exists?

**Comment by 42Bastian** [comment]
Fixed.
